#include <stdio.h>
#include <btstack.h>
#include <pico/cyw43_arch.h>
#include <pico/btstack_cyw43.h>
#include <hardware/adc.h>
#include <pico/stdlib.h>
#include "profile.h"
#include "status.h"

#define HEARTBEAT_PERIOD_MS 100
#define APP_AD_FLAGS 0x06

enum
{
    SOSC_COUNTS       = (1 << 20),
    SOSC_DET_ITER     = 16,  // Number of measurements before making decision
    SOSC_DET_TH       = 10,  // Number of times in threshold (votes) to declare detected
    SOSC_VOTE_MIN_TH  = 5,   // Threshold: 2^20 / Fclk * dF
                             // Fclk = 120 MHz
                             // dF = 1 kHz (change in frequency with phone)
    SOSC_VOTE_MAX_TH  = 500, // Significant frequency changes from charger ping ignored
                             // dF = 100 kHz
};

extern const uint8_t profile_data[]; // Autogenerated for GATT profile

// Data

static uint8_t btAdvertisement[] = {
    // Flags general discoverable
    2, BLUETOOTH_DATA_TYPE_FLAGS, APP_AD_FLAGS,
    // Name
    1+7, BLUETOOTH_DATA_TYPE_COMPLETE_LOCAL_NAME, 'S', 'C', 'W', ' ', 'M', 'C', 'M',
    3, BLUETOOTH_DATA_TYPE_COMPLETE_LIST_OF_16_BIT_SERVICE_CLASS_UUIDS, 0x1a, 0x18,
};

static btstack_timer_source_t btTimer;
static btstack_packet_callback_registration_t btPacketRegistration;

static struct
{
    // Phone detection
    int16_t soscCountsPrev;
    uint8_t soscDetectVote;
    uint8_t soscDetectIter;
} uData;

// Bluetooth events

static void packetHandler(uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size) {
    UNUSED(size);
    UNUSED(channel);

    if (packet_type != HCI_EVENT_PACKET) return;

    uint8_t event_type = hci_event_packet_get_type(packet);
    switch (event_type) {
        case BTSTACK_EVENT_STATE:
            if (btstack_event_state_get_state(packet) == HCI_STATE_WORKING) {
                // Bluetooth running

                // Setup advertisements
                uint16_t adv_int_min = 800;
                uint16_t adv_int_max = 800;
                uint8_t adv_type = 0;
                bd_addr_t null_addr;
                memset(null_addr, 0, 6);
                gap_advertisements_set_params(adv_int_min, adv_int_max, adv_type, 0, null_addr, 0x07, 0x00);

                gap_advertisements_set_data(sizeof(btAdvertisement), btAdvertisement);
                gap_advertisements_enable(1);

                statusSet(STATUS_IDLE);
            }
            break;

        default:
            break;
    }
}

// Remote read / write to Bluetooth attribute

union
{
    uint32_t value;
    uint8_t bytes[4];
} counter;
static uint16_t attRead(hci_con_handle_t connection_handle, uint16_t att_handle, uint16_t offset, uint8_t* buffer, uint16_t buffer_size) {
    UNUSED(connection_handle);

    if (att_handle == ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_DIGITAL_01_VALUE_HANDLE) {
        return att_read_callback_handle_blob(counter.bytes, sizeof(counter), offset, buffer, buffer_size);
    }
    return 0;
}

static int attWrite(hci_con_handle_t connection_handle, uint16_t att_handle, uint16_t transaction_mode, uint16_t offset, uint8_t* buffer, uint16_t buffer_size) {
    UNUSED(transaction_mode);
    UNUSED(offset);
    UNUSED(buffer_size);

    // Write to characteristic
    if (att_handle == ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_DIGITAL_01_VALUE_HANDLE) {
        // if (buffer_size > 0) {
        //     counter = buffer[0];
        // }
    }
    return 0;
}

// Periodic update

static void update(struct btstack_timer_source* ts) {
    // Count sense oscillator edge transitions
    int16_t counts = 0;
    bool valPrev = gpio_get(15);
    for (int i = 0; i < SOSC_COUNTS; ++i) {
        bool val = gpio_get(15);
        if (val != valPrev) {
            ++counts;
        }
        valPrev = val;
    }

    // Edge transition within threshold = 1 vote
    // Detect if enough consecutive votes
    int16_t countDelta = abs(uData.soscCountsPrev - counts);
    if (countDelta > SOSC_VOTE_MIN_TH && countDelta < SOSC_VOTE_MAX_TH) {
        ++uData.soscDetectVote;
    }

    // Make decision after measurements
    bool detected = false;
    ++uData.soscDetectIter;
    if (uData.soscDetectIter >= SOSC_DET_ITER) {
        if (uData.soscDetectVote >= SOSC_DET_TH) {
            detected = true;
            // Update counts to avoid re-detection
            uData.soscCountsPrev = counts;
        }
        else if (uData.soscDetectVote == 0) {
            // Update counts when certain is idle
            uData.soscCountsPrev = counts;
        }
        // Update for next measurement
        uData.soscDetectVote = 0;
        uData.soscDetectIter = 0;
    }



    // Pulse LED if detected
    if (detected) {
        gpio_set_mask(1);
    }
    else {
        gpio_clr_mask(1);
    }


    // Charger test
    if (gpio_get(12)) {
        statusSet(STATUS_TRANSIT);
    }
    else {
        statusSet(STATUS_IDLE);
    }

    statusUpdate();

    // Restart timer
    btstack_run_loop_set_timer(ts, HEARTBEAT_PERIOD_MS);
    btstack_run_loop_add_timer(ts);
}

// Init

int main() {
    // Initialize CYW43 driver architecture (will enable BT if/because CYW43_ENABLE_BLUETOOTH == 1)
    if (cyw43_arch_init()) {
        return 1; // Can't use LED if this fails
    }

    gpio_init(0);
    gpio_set_dir(0, GPIO_OUT);
    gpio_init(15);
    gpio_set_dir(15, GPIO_IN);
    gpio_init(12);
    gpio_set_dir(12, GPIO_IN);

    // Initialize bluetooth
    l2cap_init();
    sm_init();

    btPacketRegistration.callback = &packetHandler;
    hci_add_event_handler(&btPacketRegistration);

    btTimer.process = &update;
    btstack_run_loop_set_timer(&btTimer, HEARTBEAT_PERIOD_MS);
    btstack_run_loop_add_timer(&btTimer);

    att_server_init(profile_data, attRead, attWrite);
    att_server_register_packet_handler(packetHandler);

    // Turn on bluetooth
    if (hci_power_control(HCI_POWER_ON)) {
        statusSet(STATUS_BT_ERR);
    }

    // In this loop the Bluetooth events will run
    while (1) {
    }
    return 0;
}