#include <stdio.h>
#include <btstack.h>
#include <pico/cyw43_arch.h>
#include <pico/btstack_cyw43.h>
#include <hardware/adc.h>
#include <pico/stdlib.h>
#include "profile.h"
#include "status.h"

#define HEARTBEAT_PERIOD_MS 1000
#define APP_AD_FLAGS 0x06

extern const uint8_t profile_data[]; // Autogenerated for GATT profile

// Data

static uint8_t btAdvertisement[] = {
    // Flags general discoverable
    2, BLUETOOTH_DATA_TYPE_FLAGS, APP_AD_FLAGS,
    // Name
    1+7, BLUETOOTH_DATA_TYPE_COMPLETE_LOCAL_NAME, 'S', 'C', 'W', ' ', 'M', 'C', 'M',
    3, BLUETOOTH_DATA_TYPE_COMPLETE_LIST_OF_16_BIT_SERVICE_CLASS_UUIDS, 0x1a, 0x18,
};

static btstack_timer_source_t btHeartbeat;
static btstack_packet_callback_registration_t btPacketRegistration;

// Bluetooth events

static void packetHandler(uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size) {
    UNUSED(size);
    UNUSED(channel);

    if (packet_type != HCI_EVENT_PACKET) return;

    uint8_t event_type = hci_event_packet_get_type(packet);
    switch (event_type) {
        case BTSTACK_EVENT_STATE:
            if (btstack_event_state_get_state(packet) == HCI_STATE_WORKING) {
                // Bluetooth running

                // Setup advertisements
                uint16_t adv_int_min = 800;
                uint16_t adv_int_max = 800;
                uint8_t adv_type = 0;
                bd_addr_t null_addr;
                memset(null_addr, 0, 6);
                gap_advertisements_set_params(adv_int_min, adv_int_max, adv_type, 0, null_addr, 0x07, 0x00);

                gap_advertisements_set_data(sizeof(btAdvertisement), btAdvertisement);
                gap_advertisements_enable(1);

                statusSet(STATUS_OK);
            }
            break;

        default:
            break;
    }
}

static void heartbeatHandler(struct btstack_timer_source* ts) {
    // Restart timer
    btstack_run_loop_set_timer(ts, HEARTBEAT_PERIOD_MS);
    btstack_run_loop_add_timer(ts);
}


// Remote read / wrote to attributes
uint8_t counter = 0;
static uint16_t attRead(hci_con_handle_t connection_handle, uint16_t att_handle, uint16_t offset, uint8_t* buffer, uint16_t buffer_size) {
    UNUSED(connection_handle);

    if (att_handle == ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_DIGITAL_01_VALUE_HANDLE) {
        return att_read_callback_handle_blob(&counter, sizeof(counter), offset, buffer, buffer_size);
    }
    return 0;
}

static int attWrite(hci_con_handle_t connection_handle, uint16_t att_handle, uint16_t transaction_mode, uint16_t offset, uint8_t* buffer, uint16_t buffer_size) {
    UNUSED(transaction_mode);
    UNUSED(offset);
    UNUSED(buffer_size);

    // Write to characteristic
    if (att_handle == ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_DIGITAL_01_VALUE_HANDLE) {
        if (buffer_size > 0) {
            counter = buffer[0];
        }
    }
    return 0;
}

int main() {
    // Initialize CYW43 driver architecture (will enable BT if/because CYW43_ENABLE_BLUETOOTH == 1)
    if (cyw43_arch_init()) {
        return 1; // Can't use LED if this fails
    }

    // Initialize bluetooth
    l2cap_init();
    sm_init();

    btPacketRegistration.callback = &packetHandler;
    hci_add_event_handler(&btPacketRegistration);

    btHeartbeat.process = &heartbeatHandler;
    btstack_run_loop_set_timer(&btHeartbeat, HEARTBEAT_PERIOD_MS);
    btstack_run_loop_add_timer(&btHeartbeat);

    att_server_init(profile_data, attRead, attWrite);
    att_server_register_packet_handler(packetHandler);

    // Turn on bluetooth
    if (hci_power_control(HCI_POWER_ON)) {
        statusSet(STATUS_BT_ERR);
    }

    // Loop is only for updating status LED
    // Bluetooth update is done via events
    while (1) {
        statusUpdate();
        sleep_ms(500);
    }
    return 0;
}